### ISSUE TITLE
Invalid Dimension error when opening CSRGARAG

### ISSUE THREAD

**Issue by turn1pwastaken** [NinjaWeedle/CSRacing#2]
I try and open the program through cesium, and it throws this error
![Capture 1](https://github.com/NinjaWeedle/CSRacing/assets/87254467/6db51d9f-9d41-42e8-8b92-1c435d50ba81)

**Comment by turn1pwastaken** [comment]
Am I supposed to boot it through cesium???

**Comment by NinjaWeedle** [comment]
You booted CSRGARAG first without ever launching CSRACING. CSRGARAG is only meant to be launched from CSRACING, hence why CSRACING has a cesium icon and CSRGARAG does not.

**Comment by NinjaWeedle** [comment]
Closing as resolved.
